apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: startupos

resources:
  - namespace.yaml
  - postgres.yaml
  - pvc.yaml
  - odoo-configmap.yaml
  - odoo-deployment.yaml
  - odoo-service.yaml

commonLabels:
  project: thestartupos
  managed-by: kustomize
