apiVersion: v1
kind: Service
metadata:
  name: startupos-tenant-odoo
  namespace: startupos
  labels:
    app: startupos
    component: odoo
    role: tenant
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8069
      name: http
      protocol: TCP
    - port: 8072
      targetPort: 8072
      name: longpoll
      protocol: TCP
