apiVersion: v1
kind: ConfigMap
metadata:
  name: startupos-tenant-odoo-config
  namespace: startupos
  labels:
    app: startupos
    component: odoo
data:
  odoo.conf: |
    [options]
    addons_path = __ADDONS_PATH__
    data_dir = /var/lib/odoo
    admin_passwd = __ODOO_MASTER_PASS__
    http_port = 8069
    proxy_mode = True
    workers = 2
    limit_memory_soft = 536870912
    limit_memory_hard = 1073741824
    limit_request = 8192
    limit_time_cpu = 60
    limit_time_real = 120
    max_cron_threads = 1
    log_level = info
    log_handler = :INFO
    without_demo = True
    list_db = True
    dbfilter = ^%d$
    db_name = False
    db_host = __DB_HOST__
    db_port = 5432
    db_user = odoo
    db_password = __DB_PASSWORD__
    server_wide_modules = base,web
