apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: startupos-tenant-odoo-data
  namespace: startupos
  labels:
    app: startupos
    component: odoo
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: startupos-tenant-odoo-addons
  namespace: startupos
  labels:
    app: startupos
    component: odoo
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
